name: Update main

on:
  push:
    branches:
      - uat

jobs:
  update-main:
    name: Merge uat into main after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'uat'
          target: 'main'
      - name: Delete closed PR branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ github.token }}
          numbers: ${{github.event.pull_request.number}}
