name: Update main & Delete pr

on:
  push:
    branches:
      - uat

jobs:
  update-main:
    name: Merge uat into main after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'uat'
          target: 'main'
  delete-branch:
    name: delete branch on close pr
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
