name: Update main & Delete pr

on:
  pull_request:
    branches: ['uat']
    types: [closed]

jobs:
  update-main:
    name: Merge uat into main
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'uat'
          target: 'main'
  delete-branch:
    if: ${{ always() }}
    needs: [update-main]
    name: delete branch on close pr
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
