name: CI

on:
  push:
    branches:
      - develop
      - uat
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Environment setup
        id: env-setup
        run: |
          if [ "${{ github.ref_name }}" == "develop" ]; then
            echo "ASSEMBLE=StageRelease" >> "$GITHUB_OUTPUT"
            echo "FILE=stage" >> "$GITHUB_OUTPUT"
            echo "GROUPS=qa-testers" >> "$GITHUB_OUTPUT"
            echo "RELEASE_NOTE=QA" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref_name }}" == "uat" ]; then
            echo "ASSEMBLE=UATRelease" >> "$GITHUB_OUTPUT"
            echo "FILE=uat" >> "$GITHUB_OUTPUT"
            echo "GROUPS=uat-testers" >> "$GITHUB_OUTPUT"
            echo "RELEASE_NOTE=UAT" >> "$GITHUB_OUTPUT"
          else
            echo "ASSEMBLE=ProdRelease" >> "$GITHUB_OUTPUT"
            echo "FILE=prod" >> "$GITHUB_OUTPUT"
            echo "GROUPS=prod-testers" >> "$GITHUB_OUTPUT"
            echo "RELEASE_NOTE=PRODUCTION" >> "$GITHUB_OUTPUT"
          fi

      - name: Run develop script
        id: develop-script
        if: github.ref_name == 'develop'
        env:
          ASSEMBLE: ${{ steps.env-setup.outputs.ASSEMBLE }}
          FILE: ${{ steps.env-setup.outputs.FILE }}
          GROUPS: ${{ steps.env-setup.outputs.GROUPS }}
          RELEASE_NOTE: ${{ steps.env-setup.outputs.GROUPS }}
        run: |
          echo Hello, Development!
          echo ---
          echo Ref_name, ${{ github.ref_name }}
          echo Ref, ${{ github.ref }}
          echo ce$ASSEMBLE 
          echo ce$FILEce123
          echo ce${{ env.GROUPS }}
          echo ce${{ env.RELEASE_NOTE }}ce123
      
      - name: Run uat script
        id: uat-script
        if: github.ref_name == 'uat'
        env:
          ASSEMBLE: ${{ steps.env-setup.outputs.ASSEMBLE }}
          FILE: ${{ steps.env-setup.outputs.FILE }}
          GROUPS: ${{ steps.env-setup.outputs.GROUPS }}
          RELEASE_NOTE: ${{ steps.env-setup.outputs.GROUPS }}
        run: |
          echo Hello, UAT!
          echo ---
          echo Ref_name, ${{ github.ref_name }}
          echo Ref, ${{ github.ref }}
          echo $ASSEMBLE $FILE $GROUPS $RELEASE_NOTE
          
      - name: Generate App Version Name
        if: startsWith(github.ref_name, 'v')
        run: VERSION_NAME=$(git tag -l | cut -c2-)
      
      - name: Run production script
        if: startsWith(github.ref_name, 'v')
        run: |
          APP_VERSION=$(git tag -l | cut -c2-)
          echo Hello, Production-${{ env.VERSION_NAME }}!
          echo Hello, Production-${{ env.APP_VERSION }}!
          echo Hello, Production-$(git tag -l | cut -c2-)!
          echo ---
          echo Ref_name, ${{ github.ref_name }}
          echo Ref, ${{ github.ref }}
