name: CI

on:
  push:
    branches:
      - develop
      - uat
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run develop script
        if: github.ref_name == 'develop'
        run: |
          echo Hello, Development!
          echo ---
          echo Ref_name, ${{ github.ref_name }}
          echo Ref, ${{ github.ref }}
      
      - name: Run uat script
        if: github.ref_name == 'uat'
        run: |
          echo Hello, UAT!
          echo ---
          echo Ref_name, ${{ github.ref_name }}
          echo Ref, ${{ github.ref }}
          
      - name: Generate App Version Name
        if: startsWith(github.ref_name, 'v')
        run: echo "VERSION_NAME=$(git tag -l | cut -c2-)" >> $APP_VERSION
      
      - name: Run production script
        if: startsWith(github.ref_name, 'v')
        run: |
          echo Hello, Production-${{ env.VERSION_NAME }}!
          echo Hello, Production-${{ env.APP_VERSION }}!
          echo ---
          echo Ref_name, ${{ github.ref_name }}
          echo Ref, ${{ github.ref }}
