name: CI

on:
  push:
    branches:
      - develop
      - uat
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Environment setup
        id: env-setup
        run: |
          if [ "${{ github.ref_name }}" == "develop" ]; then
            echo "ASSEMBLE=StageRelease" >> $GITHUB_ENV
            echo "FILE=stage" >> $GITHUB_ENV
            echo "GROUPS=qa-testers" >> $GITHUB_ENV
            echo "RELEASE_NOTE=QA" >> $GITHUB_ENV
            git fetch --tags
            git tag -l | cut -c2-
            # echo "VERSION_NAME=$(git tag -l | cut -c2-)" >> $GITHUB_ENV
            # echo "GIT_LOG=$(git log -1 --pretty=short)" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "uat" ]; then
            echo "ASSEMBLE=UATRelease" >> $GITHUB_ENV
            echo "FILE=uat" >> $GITHUB_ENV
            echo "GROUPS=uat-testers" >> $GITHUB_ENV
            echo "RELEASE_NOTE=UAT" >> $GITHUB_ENV
          else
            echo "ASSEMBLE=ProdRelease" >> $GITHUB_ENV
            echo "FILE=prod" >> $GITHUB_ENV
            echo "GROUPS=prod-testers" >> $GITHUB_ENV
            echo "RELEASE_NOTE=PRODUCTION" >> $GITHUB_ENV
            echo "VERSION_NAME=$(git tag -l | cut -c2-)" >> $GITHUB_ENV
          fi

      - name: Run script
        id: script
        if:
          contains('
            develop
            uat
          ', github.ref_name)
        run: |
          echo Ref_name, ${{ github.ref_name }}
          echo Ref, ${{ github.ref }}
          echo ---
          echo ${{ env.ASSEMBLE }}
          echo ${{ env.FILE }}
          echo ${{ env.GROUPS }}
          echo ${{ env.RELEASE_NOTE }}
          echo ${{ env.GIT_LOG }}
          echo ${{ env.VERSION_NAME }}
      
      - name: Run production script
        if: startsWith(github.ref_name, 'v')
        run: |
          echo Hello, Production-$(git tag -l | cut -c2-)
          echo ---
          echo Ref_name, ${{ github.ref_name }}
          echo Ref, ${{ github.ref }}
          echo ---
          echo ${{ env.ASSEMBLE }}
          echo ${{ env.FILE }}
          echo ${{ env.GROUPS }}
          echo ${{ env.RELEASE_NOTE }}
          echo ${{ env.VERSION_NAME }}
