name: CI

on:
  push:
    branches:
      - develop
      - uat
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run develop script
        id: develop-script
        if: github.ref_name == 'develop'
        run: |
          echo Hello, Development!
          echo ---
          echo Ref_name, ${{ github.ref_name }}
          echo Ref, ${{ github.ref }}
          echo "ENV_DATA1=development1" >> "$GITHUB_OUTPUT"
          echo "ENV_DATA2=development2" >> "$GITHUB_OUTPUT"
          echo "ENV_DATA3=development3" >> "$GITHUB_OUTPUT"

      - name: Copy data
        if: github.ref_name == 'develop'
        env:
          ENV_DATA1: ${{ steps.develop-script.outputs.ENV_DATA1 }}
          ENV_DATA3: ${{ steps.develop-script.outputs.ENV_DATA3 }}
          NEW_DATA: ${{ steps.develop-script.outputs.ENV_DATA2 }}
        run: |
          echo Hello, Development!
          echo ---
          echo Ref_name, ${{ github.ref_name }}
          echo Ref, ${{ github.ref }}
          echo $ENV_DATA3 $ENV_DATA1
          echo new_data $NEW_DATA
      
      - name: Run uat script
        if: github.ref_name == 'uat'
        run: |
          echo Hello, UAT!
          echo ---
          echo Ref_name, ${{ github.ref_name }}
          echo Ref, ${{ github.ref }}
          
      - name: Generate App Version Name
        if: startsWith(github.ref_name, 'v')
        run: VERSION_NAME=$(git tag -l | cut -c2-)
      
      - name: Run production script
        if: startsWith(github.ref_name, 'v')
        run: |
          APP_VERSION=$(git tag -l | cut -c2-)
          echo Hello, Production-${{ env.VERSION_NAME }}!
          echo Hello, Production-${{ env.APP_VERSION }}!
          echo Hello, Production-$(git tag -l | cut -c2-)!
          echo ---
          echo Ref_name, ${{ github.ref_name }}
          echo Ref, ${{ github.ref }}
