name: Docker Image Versioning 

on:
  push:
    branches:
      - develop
    tags:
      - docker*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker pull
        run: |
          docker pull alpine:latest
